// The example artifact each schema page shows beside the schema itself: a real
// validating instance from this repository, never a snippet written for the page.
//
// One inventory rather than a table inside the English page, because four things read
// it and they must read the same answer: both pages render the panel, the translation
// projection enumerates the prose inside the instance, the build validates the
// localized instance against the schema it exemplifies, and the drift gate compares
// every translation against the example file's current revision.
//
// The note is English page copy keyed by `noteKey`; a translated page carries its own
// note under the same key, so the two never fall out of step over which panel is which.

/** The formats an example is published in, which is what decides how a translation
 *  reads the prose inside it: a JSON instance, or a markdown document whose YAML
 *  frontmatter is the part the schema validates. */
export type ExampleFormat = 'json' | 'markdown';

export interface SchemaExample {
   /** Repository-root-relative path to the instance. */
   file: string;
   format: ExampleFormat;
   /** The file's own name, shown on the tab. */
   label: string;
   /** The key both the English note and every translated one are written under. */
   noteKey: ExampleNoteKey;
}

/** Schema name (its file's stem) to the example that instance-checks it. */
export const SCHEMA_EXAMPLES: Record<string, SchemaExample> = {
   'context-manifest': {
      file: 'examples/monorepo/leji.json',
      format: 'json',
      label: 'leji.json',
      noteKey: 'manifest',
   },
   'context-index': {
      file: 'examples/monorepo/docs/context-index.json',
      format: 'json',
      label: 'context-index.json',
      noteKey: 'index',
   },
   'context-changelog': {
      file: 'examples/monorepo/docs/context-changelog.json',
      format: 'json',
      label: 'context-changelog.json',
      noteKey: 'changelog',
   },
   'agent-profile': {
      file: 'examples/monorepo/docs/agents/thought-partner.md',
      format: 'markdown',
      label: 'thought-partner.md',
      noteKey: 'agentProfile',
   },
   'decision-record': {
      file: 'examples/monorepo/docs/decisions/0001-adopt-leji.md',
      format: 'markdown',
      label: '0001-adopt-leji.md',
      noteKey: 'decisionRecord',
   },
};

/** The note above each example panel, in English. */
export const EXAMPLE_NOTES = {
   manifest: 'A conforming manifest at a repository root.',
   index: 'A generated context index, regenerated by the CLI on change.',
   changelog: 'A machine-readable changelog of context layer changes.',
   agentProfile:
      'A conforming agent profile. This schema validates the YAML frontmatter; the markdown body beneath it is free-form prose.',
   decisionRecord:
      'A conforming decision record. This schema validates the YAML frontmatter; the markdown body carries context, decision, and consequences.',
} as const;

export type ExampleNoteKey = keyof typeof EXAMPLE_NOTES;

/** The example for one schema. Every schema has one and the pages assert it, so a
 *  schema added without an instance to show fails the build rather than rendering a
 *  reference page with half its evidence missing. */
export function schemaExample(name: string): SchemaExample {
   const example = SCHEMA_EXAMPLES[name];
   if (!example) throw new Error(`no example instance for the ${name} schema: add one to src/data/schema-examples.ts`);
   return example;
}
