"""The declaration offer and the generated CI/hook contract, against the shared
fixtures. The manager is never really spawned: every consent path runs through the
injected fake, which records instead of running."""

from __future__ import annotations

from pathlib import Path

import pytest

from leji.cigen import (
    CI_MARKER,
    CI_PROVIDERS,
    build_ci_file,
    ci_variants,
    hook_body,
    husky_block,
    resolve_ci_job,
    sh_quote,
)
from leji.dependency import (
    AddResult,
    DependencyIO,
    DependencyOffer,
    dependency_add_failed,
    offer_dependency,
)
from leji.ecosystem import (
    consent_disclosure,
    detect_ecosystem,
    manager_runner_argv,
    runner_argv,
)
from leji.init_cmd import ensure_ci_workflow, ensure_local_hook

REPO_ROOT = Path(__file__).resolve().parents[3]
CASES = REPO_ROOT / "fixtures" / "ecosystem"
GOLDENS = REPO_ROOT / "fixtures" / "ci-goldens"

CI_REL = {
    "github": ".github/workflows/leji.yml",
    "gitlab": ".gitlab-ci.yml",
    "circleci": ".circleci/config.yml",
    "azure": ".azure-pipelines/leji.yml",
}

MANAGERS = ["npm", "pnpm", "yarn", "bun", "uv", "poetry", "pdm", "pipenv", "go"]
DECLARED_PKG = '{\n  "name": "demo",\n  "devDependencies": { "@leji-org/leji": "^1" }\n}\n'


def golden(name: str) -> str:
    return (GOLDENS / name).read_text(encoding="utf-8")


def plant(tmp_path: Path, files: dict[str, str], name: str = "root") -> Path:
    root = tmp_path / name
    root.mkdir(parents=True, exist_ok=True)
    for rel, body in files.items():
        (root / rel).write_text(body, encoding="utf-8")
    return root


# --- the goldens ----------------------------------------------------------


def test_ci_variants_match_goldens() -> None:
    variants = ci_variants()
    assert len(variants) == len(CI_PROVIDERS) * 12
    for provider, key, body in variants:
        assert body == golden(f"{provider}-{key}.yml"), f"{provider}/{key}"


def test_hook_goldens() -> None:
    for manager in MANAGERS:
        argv = manager_runner_argv(manager)
        assert argv is not None
        assert hook_body(argv) == golden(f"hook-{manager}.sh"), manager
        assert husky_block(argv) == golden(f"husky-{manager}.sh"), manager
    assert hook_body(["leji"]) == golden("hook-fallback.sh")
    assert husky_block(["leji"]) == golden("husky-fallback.sh")


def test_sh_quote_and_hook_shape() -> None:
    assert sh_quote("pnpm") == "'pnpm'"
    assert sh_quote("we'ird") == "'we'\\''ird'"
    assert sh_quote("a b") == "'a b'"
    assert sh_quote("x$HOME") == "'x$HOME'"
    body = hook_body(["weird bin", "quo'te", "$HOME", "`cmd`", "*"])
    assert "'weird bin' 'quo'\\''te' '$HOME' '`cmd`' '*' validate || exit 1" in body
    assert "echo 'leji: stored index is stale; run `leji index` and stage the result.' >&2" in body
    for argv in (["leji"], ["pnpm", "exec", "leji"], ["go", "tool", "leji"]):
        for gone in ("node_modules", "LEJI=", "$LEJI"):
            assert gone not in hook_body(argv)
            assert gone not in husky_block(argv)


def test_marker_and_legacy_job() -> None:
    for provider, key, body in ci_variants():
        if provider == "gitlab":
            assert "generated by leji ci (managed)" not in body
            assert body.startswith("# >>> leji ci (managed) >>>\n")
        else:
            assert body.startswith(CI_MARKER + "\n"), f"{provider}/{key}"
    for provider in ("github", "circleci", "azure"):
        before = golden(f"legacy-1.3-{provider}-fallback.yml")
        assert golden(f"{provider}-node-fallback.yml") == CI_MARKER + "\n" + before


def test_unpinned_disclosure_appears_once_only_where_earned() -> None:
    for provider, key, body in ci_variants():
        hits = [line for line in body.split("\n") if "is installed unpinned here" in line]
        wants = key in ("poetry-local", "pdm-local", "pipenv-local") or (
            key == "uv-local" and provider != "github"
        )
        assert len(hits) == (1 if wants else 0), f"{provider}/{key}"
    assert "astral-sh/setup-uv@v5" in golden("github-uv-local.yml")
    assert "pip install uv" not in golden("github-uv-local.yml")
    assert "pip install uv && uv sync --locked" in golden("gitlab-uv-local.yml")


# --- the table ------------------------------------------------------------

LOCAL_ROOTS = {
    "pnpm": {"package.json": DECLARED_PKG, "pnpm-lock.yaml": ""},
    "npm": {"package.json": DECLARED_PKG, "package-lock.json": ""},
    "uv": {
        "pyproject.toml": '[project]\nname = "d"\nversion = "0"\ndependencies = ["leji"]\n',
        "uv.lock": "",
    },
    "go": {
        "go.mod": "module example.com/d\n\ngo 1.24.0\n\n"
        "tool github.com/leji-org/leji/packages/sdk-go/cmd/leji\n"
    },
}


@pytest.mark.parametrize("manager", sorted(LOCAL_ROOTS))
@pytest.mark.parametrize("provider", CI_PROVIDERS)
def test_ci_table_local_jobs(tmp_path: Path, manager: str, provider: str) -> None:
    root = plant(tmp_path, LOCAL_ROOTS[manager], f"{manager}-{provider}")
    result = ensure_ci_workflow(str(root), provider)
    assert result.action == "created"
    assert (root / CI_REL[provider]).read_text(encoding="utf-8") == golden(
        f"{provider}-{manager}-local.yml"
    )


def test_ci_table_fallbacks(tmp_path: Path) -> None:
    cases = [
        ({"package.json": DECLARED_PKG}, "node-fallback"),
        ({"package.json": '{"name":"demo"}\n', "package-lock.json": ""}, "node-fallback"),
        ({"package.json": "{}\n", "package-lock.json": "", "yarn.lock": ""}, "node-fallback"),
        ({"package.json": '{"packageManager":"hermit@1.0.0"}\n'}, "node-fallback"),
        ({"pyproject.toml": '[project]\nname = "d"\nversion = "0"\n'}, "python-fallback"),
        ({"requirements.txt": "requests\n"}, "python-fallback"),
        ({"go.mod": "module example.com/d\n\ngo 1.23\n"}, "go-fallback"),
        ({"go.mod": "module example.com/d\n\ngo 1.24.0\n"}, "go-fallback"),
        (
            {"package.json": "{}\n", "pyproject.toml": '[project]\nname="d"\nversion="0"\n'},
            "node-fallback",
        ),
    ]
    for i, (files, key) in enumerate(cases):
        root = plant(tmp_path, files, f"fb{i}")
        ensure_ci_workflow(str(root), "github")
        assert (root / CI_REL["github"]).read_text(encoding="utf-8") == golden(
            f"github-{key}.yml"
        ), key


# --- ownership ------------------------------------------------------------


def test_ci_ownership_upgrades_a_legacy_file(tmp_path: Path) -> None:
    for provider in ("github", "circleci", "azure"):
        for mode in ("local", "fallback"):
            root = plant(tmp_path, dict(LOCAL_ROOTS["pnpm"]), f"legacy-{provider}-{mode}")
            target = root / CI_REL[provider]
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(golden(f"legacy-1.3-{provider}-{mode}.yml"), encoding="utf-8")
            result = ensure_ci_workflow(str(root), provider)
            assert result.action == "updated", f"{provider}/{mode}"
            assert target.read_text(encoding="utf-8") == golden(f"{provider}-pnpm-local.yml")


def test_ci_ownership_idempotent_and_manager_change(tmp_path: Path) -> None:
    for provider in CI_PROVIDERS:
        root = plant(tmp_path, dict(LOCAL_ROOTS["uv"]), f"idem-{provider}")
        assert ensure_ci_workflow(str(root), provider).action == "created"
        after = (root / CI_REL[provider]).read_text(encoding="utf-8")
        assert ensure_ci_workflow(str(root), provider).action == "unchanged"
        assert (root / CI_REL[provider]).read_text(encoding="utf-8") == after

    change = plant(tmp_path, dict(LOCAL_ROOTS["pnpm"]), "manager-change")
    target = change / CI_REL["github"]
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(golden("github-npm-local.yml"), encoding="utf-8")
    assert ensure_ci_workflow(str(change), "github").action == "updated"
    assert target.read_text(encoding="utf-8") == golden("github-pnpm-local.yml")


def test_ci_ownership_leaves_edited_and_foreign_files_alone(tmp_path: Path) -> None:
    for provider in ("github", "circleci", "azure"):
        edited = plant(tmp_path, dict(LOCAL_ROOTS["pnpm"]), f"edited-{provider}")
        mine = golden(f"{provider}-pnpm-local.yml")
        target = edited / CI_REL[provider]
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(mine + "      - run: echo mine\n", encoding="utf-8")
        result = ensure_ci_workflow(str(edited), provider)
        assert result.action == "manual" and result.snippet
        assert target.read_text(encoding="utf-8") == mine + "      - run: echo mine\n"

        foreign = plant(tmp_path, dict(LOCAL_ROOTS["pnpm"]), f"foreign-{provider}")
        ftarget = foreign / CI_REL[provider]
        ftarget.parent.mkdir(parents=True, exist_ok=True)
        ftarget.write_text("name: someone-elses-pipeline\n", encoding="utf-8")
        assert ensure_ci_workflow(str(foreign), provider).action == "manual"
        assert ftarget.read_text(encoding="utf-8") == "name: someone-elses-pipeline\n"


def test_ci_ownership_is_provider_scoped(tmp_path: Path) -> None:
    """The same bytes are leji's at one provider's path and somebody else's at
    another's, so a digest match must be provider-scoped."""
    cross = [
        ("github", "legacy-1.3-circleci-local.yml"),
        ("github", "legacy-1.3-azure-fallback.yml"),
        ("circleci", "legacy-1.3-github-local.yml"),
        ("circleci", "legacy-1.3-azure-local.yml"),
        ("azure", "legacy-1.3-github-fallback.yml"),
        ("azure", "legacy-1.3-circleci-fallback.yml"),
    ]
    for i, (provider, foreign) in enumerate(cross):
        root = plant(tmp_path, dict(LOCAL_ROOTS["pnpm"]), f"cross{i}")
        target = root / CI_REL[provider]
        target.parent.mkdir(parents=True, exist_ok=True)
        body = golden(foreign)
        target.write_text(body, encoding="utf-8")
        assert ensure_ci_workflow(str(root), provider).action == "manual", f"{foreign}@{provider}"
        assert target.read_text(encoding="utf-8") == body
    for provider in ("github", "circleci", "azure"):
        root = plant(tmp_path, dict(LOCAL_ROOTS["pnpm"]), f"own-{provider}")
        target = root / CI_REL[provider]
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(golden(f"legacy-1.3-{provider}-local.yml"), encoding="utf-8")
        assert ensure_ci_workflow(str(root), provider).action == "updated"


def test_gitlab_owns_only_its_block(tmp_path: Path) -> None:
    root = plant(tmp_path, dict(LOCAL_ROOTS["pnpm"]), "gitlab-merge")
    target = root / ".gitlab-ci.yml"
    target.write_text("stages:\n  - test\n", encoding="utf-8")
    assert ensure_ci_workflow(str(root), "gitlab").action == "updated"
    merged = target.read_text(encoding="utf-8")
    assert merged.startswith("stages:\n  - test\n")
    assert golden("gitlab-pnpm-local.yml") in merged


# --- the consent path -----------------------------------------------------


def _fake_io(answer: str, result: AddResult):
    runs: list[tuple[str, list[str], str]] = []
    questions: list[str] = []

    def read_line(question: str, fallback: str) -> str:
        questions.append(question)
        return answer

    def run(bin_name: str, args: list[str], cwd: str) -> AddResult:
        runs.append((bin_name, args, cwd))
        return result

    return DependencyIO(read_line=read_line, run=run), runs, questions


def _offer(
    capsys, fixture: str, interactive: bool, answer: str = "", result: AddResult | None = None
):
    root = str(CASES / fixture)
    io, runs, _ = _fake_io(answer, result or AddResult(started=True))
    offer = offer_dependency(root, detect_ecosystem(root), interactive, io)
    return offer, capsys.readouterr().out, runs


def test_offer_yes_runs_the_manager(capsys) -> None:
    offer, out, runs = _offer(capsys, "node-pnpm-lock", True, "y")
    assert runs == [("pnpm", ["add", "-D", "@leji-org/leji"], str(CASES / "node-pnpm-lock"))]
    assert "Detected pnpm (pnpm-lock.yaml)." in out
    assert consent_disclosure("pnpm") in out
    assert "Running: pnpm add -D @leji-org/leji" in out
    assert "Declared @leji-org/leji; a clean install now brings leji." in out
    assert offer == DependencyOffer(
        offered=True,
        ran=True,
        command=["pnpm", "add", "-D", "@leji-org/leji"],
        exit_code=0,
        signal=None,
    )
    assert not dependency_add_failed(offer)


def test_disclosure_precedes_the_prompt(capsys) -> None:
    _, out, _ = _offer(capsys, "node-pnpm-lock", True, "n")
    assert out.index("Detected pnpm") < out.index(consent_disclosure("pnpm"))
    offer, quiet, runs = _offer(capsys, "node-pnpm-lock", False, "y")
    assert "This runs" not in quiet and runs == []
    # Nothing ran, so there is no exit code and no signal to report.
    assert offer == DependencyOffer(
        offered=True,
        ran=False,
        command=["pnpm", "add", "-D", "@leji-org/leji"],
        exit_code=None,
        signal=None,
    )
    for fixture, binary in (("python-uv", "uv"), ("go-1.24", "go"), ("node-npm-lock", "npm")):
        _, text, _ = _offer(capsys, fixture, True, "n")
        assert consent_disclosure(binary) in text


def test_decline_runs_nothing(capsys) -> None:
    for answer in ("n", "no", "q", "N"):
        offer, out, runs = _offer(capsys, "node-pnpm-lock", True, answer)
        assert runs == [] and not dependency_add_failed(offer)
        assert offer == DependencyOffer(
            offered=True,
            ran=False,
            command=["pnpm", "add", "-D", "@leji-org/leji"],
            exit_code=None,
            signal=None,
        )
        assert "Skipped; declare it later with:\n   pnpm add -D @leji-org/leji" in out


def test_failure_branches(capsys) -> None:
    offer, out, _ = _offer(capsys, "python-uv", True, "y", AddResult(started=True, exit_code=1))
    assert "uv exited 1; run it yourself:\n   uv add --dev leji" in out
    assert offer == DependencyOffer(
        offered=True, ran=True, command=["uv", "add", "--dev", "leji"], exit_code=1, signal=None
    )
    assert dependency_add_failed(offer)

    # A signalled manager has no exit code of its own: the signal is the outcome.
    offer, out, _ = _offer(
        capsys, "go-1.24", True, "y", AddResult(started=True, exit_code=-1, signal="SIGTERM")
    )
    assert "go was terminated (SIGTERM); run it yourself:" in out
    assert offer == DependencyOffer(
        offered=True,
        ran=True,
        command=["go", "get", "-tool", "github.com/leji-org/leji/packages/sdk-go/cmd/leji@latest"],
        exit_code=None,
        signal="SIGTERM",
    )
    assert dependency_add_failed(offer)

    # A spawn that never started carries neither an exit code nor a signal, and is
    # still a failure: reading its null exit code as success would pass a run in
    # which nothing happened.
    offer, out, _ = _offer(capsys, "node-npm-lock", True, "y", AddResult(started=False))
    assert "npm is not on your PATH; run it yourself once it is:\n   npm i -D @leji-org/leji" in out
    assert offer == DependencyOffer(
        offered=True,
        ran=True,
        command=["npm", "i", "-D", "@leji-org/leji"],
        exit_code=None,
        signal=None,
    )
    assert dependency_add_failed(offer)


def test_signal_name_is_canonical_across_runtimes() -> None:
    """Python reports a signalled child as a negative return code; the runner turns
    that into the canonical name the other two SDKs print."""
    import subprocess

    from leji.dependency import default_dependency_io

    io = default_dependency_io()
    result = io.run("sh", ["-c", "kill -TERM $$"], ".")
    assert result.started and result.signal == "SIGTERM" and result.exit_code == -1
    assert subprocess.run(["sh", "-c", "kill -TERM $$"]).returncode == -15
    clean = io.run("sh", ["-c", "exit 7"], ".")
    assert clean.started and clean.exit_code == 7 and clean.signal == ""
    missing = io.run("leji-no-such-binary-xyz", [], ".")
    assert not missing.started


def test_never_prompts_without_a_command(capsys) -> None:
    offer, out, runs = _offer(capsys, "node-declared", True, "y")
    assert runs == []
    # `command` still names the add this repository would use; `offered` is what
    # says there is nothing to consent to, because the CLI is already declared.
    assert offer == DependencyOffer(
        offered=False,
        ran=False,
        command=["npm", "i", "-D", "@leji-org/leji"],
        exit_code=None,
        signal=None,
    )
    assert out.strip() == "The Leji CLI is already declared in package.json."
    for fixture in (
        "python-bare-pyproject",
        "python-requirements-only",
        "go-1.23-legacy",
        "node-two-lockfiles",
        "node-refused-evidence",
        "node-unreadable-manifest",
        "node-packagemanager-unknown",
        "none",
        "multiple-ecosystems",
        "composite-ambiguity",
    ):
        offer, _, runs = _offer(capsys, fixture, True, "y")
        assert runs == [], fixture
        assert not offer.offered and not offer.ran and not dependency_add_failed(offer), fixture


def test_hook_uses_the_detected_runner(tmp_path: Path) -> None:
    import subprocess

    root = plant(tmp_path, dict(LOCAL_ROOTS["pnpm"]), "hookrepo")
    subprocess.run(["git", "init", "-q"], cwd=root, check=True)
    result = ensure_local_hook(str(root))
    assert result.action == "created"
    assert (root / result.path).read_text(encoding="utf-8") == golden("hook-pnpm.sh")
    assert ensure_local_hook(str(root)).action == "unchanged"
    # And the runner the report chooses is what the hook carries.
    assert runner_argv(detect_ecosystem(str(root))) == ["pnpm", "exec", "leji"]


def test_resolve_ci_job_is_local_only_when_declared_and_locked(tmp_path: Path) -> None:
    declared_locked = detect_ecosystem(str(plant(tmp_path, dict(LOCAL_ROOTS["pnpm"]), "dl")))
    assert resolve_ci_job(declared_locked, "github").local is True
    unlocked = detect_ecosystem(str(plant(tmp_path, {"package.json": DECLARED_PKG}, "ul")))
    assert resolve_ci_job(unlocked, "github").local is False
    assert build_ci_file("github", resolve_ci_job(unlocked, "github")) == golden(
        "github-node-fallback.yml"
    )
